### 01. Tensors

Tensors are similar to NumPy's ndarrays, with the addition being that Tensors can also be used on a GPU to accelerate computing.

In [1]:
from __future__ import print_function
import torch

Note: An uninitialized matrix is declared, but does not contain definite known values before it is used. When an uninitialized matrix is created, whatever values were in the allocated memory at the time will appear as the initial values.

In [2]:
# construct a 5x3 matrix, uninitialized:
x = torch.empty(5, 3)
print(x)

tensor([[1.0653e-38, 1.0194e-38, 4.6838e-39],
        [8.4489e-39, 9.6429e-39, 8.4490e-39],
        [9.6429e-39, 9.2755e-39, 1.0286e-38],
        [9.0919e-39, 8.9082e-39, 9.2755e-39],
        [8.4490e-39, 1.0194e-38, 9.0919e-39]])


In [3]:
# construct a 5x3 randomly initialized matrix:
x = torch.rand(5, 3)
print(x)

tensor([[0.9587, 0.8335, 0.7370],
        [0.6413, 0.9160, 0.1006],
        [0.6299, 0.8921, 0.3524],
        [0.0133, 0.4765, 0.8196],
        [0.8222, 0.9329, 0.3227]])


In [4]:
# construct a matrix filled zeros and of dtype long:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
# construct a tensor directly from data:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
# create a tensor based on an existing tensor.
# these methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user.
x = x.new_ones(5, 3, dtype=torch.double) # new_* methods take in sizes
print(x)

y = torch.randn_like(x, dtype=torch.float) # override dtype, result has the same size
print(y)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.1600, -0.9529, -0.9006],
        [-1.2301, -0.0825,  1.5079],
        [-1.0778,  1.0999, -0.1254],
        [ 0.0055, -1.3581, -1.0342],
        [ 0.8180,  0.0801, -0.5212]])


In [7]:
# get its size:
print(x.size())
print(y.size())

torch.Size([5, 3])
torch.Size([5, 3])


Note: `torch.Size` is in fact a tuple, so it supports all tuple operations.