### 02. Operations

There are multiple syntaxes for operations. In the following example, we will take a look at the addition operation.

In [1]:
from __future__ import print_function
import torch

In [2]:
# addition: syntax 1
x = torch.rand(5, 3)
y = torch.rand(5, 3)
print(x)
print(y)
print(x + y)

tensor([[0.2471, 0.2641, 0.8207],
        [0.5981, 0.7604, 0.4134],
        [0.1955, 0.3937, 0.8919],
        [0.0300, 0.1266, 0.5161],
        [0.6294, 0.1684, 0.6747]])
tensor([[0.0462, 0.7882, 0.4547],
        [0.3478, 0.1413, 0.8858],
        [0.7258, 0.4699, 0.8265],
        [0.5829, 0.8737, 0.1752],
        [0.0397, 0.7404, 0.4701]])
tensor([[0.2933, 1.0523, 1.2754],
        [0.9459, 0.9017, 1.2992],
        [0.9212, 0.8636, 1.7184],
        [0.6129, 1.0003, 0.6913],
        [0.6691, 0.9087, 1.1448]])


In [3]:
# addition: syntax 2
print(torch.add(x, y))

tensor([[0.2933, 1.0523, 1.2754],
        [0.9459, 0.9017, 1.2992],
        [0.9212, 0.8636, 1.7184],
        [0.6129, 1.0003, 0.6913],
        [0.6691, 0.9087, 1.1448]])


In [4]:
# addition: providing an output tensor as argument
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[0.2933, 1.0523, 1.2754],
        [0.9459, 0.9017, 1.2992],
        [0.9212, 0.8636, 1.7184],
        [0.6129, 1.0003, 0.6913],
        [0.6691, 0.9087, 1.1448]])


In [5]:
# addition: in-place
# adds x to y
y.add_(x)
print(y)

tensor([[0.2933, 1.0523, 1.2754],
        [0.9459, 0.9017, 1.2992],
        [0.9212, 0.8636, 1.7184],
        [0.6129, 1.0003, 0.6913],
        [0.6691, 0.9087, 1.1448]])


Note: any operation that mutates a tensor in-place is post-fixed with an `_`. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

In [6]:
# you can use standard NumPy-like indexing with all bells and whistles:
print(x)
print(x[:, 1])

tensor([[0.2471, 0.2641, 0.8207],
        [0.5981, 0.7604, 0.4134],
        [0.1955, 0.3937, 0.8919],
        [0.0300, 0.1266, 0.5161],
        [0.6294, 0.1684, 0.6747]])
tensor([0.2641, 0.7604, 0.3937, 0.1266, 0.1684])


Resizing: if you want to resize/reshape tensor, you can use `torch.view`

In [7]:
x = torch.rand(4, 4)
print(x)
print('x size:', x.size())
y = x.view(16)
print(y)
print('y size:', y.size())
z = x.view(-1, 8) # the size -1 is inferred from other dimensions, i.e., 4*4/8=2
print(z)
print('z size:', z.size())

tensor([[0.1831, 0.4401, 0.9867, 0.1908],
        [0.3117, 0.4189, 0.0246, 0.9249],
        [0.9727, 0.1526, 0.7941, 0.4887],
        [0.3097, 0.9738, 0.5469, 0.3080]])
x size: torch.Size([4, 4])
tensor([0.1831, 0.4401, 0.9867, 0.1908, 0.3117, 0.4189, 0.0246, 0.9249, 0.9727,
        0.1526, 0.7941, 0.4887, 0.3097, 0.9738, 0.5469, 0.3080])
y size: torch.Size([16])
tensor([[0.1831, 0.4401, 0.9867, 0.1908, 0.3117, 0.4189, 0.0246, 0.9249],
        [0.9727, 0.1526, 0.7941, 0.4887, 0.3097, 0.9738, 0.5469, 0.3080]])
z size: torch.Size([2, 8])


If you have a one element tensor, use `.item()` to get the value as a Python number

In [8]:
x = torch.rand(4, 4)
print(x[0, 0])
print(type(x[0, 0]))
print(x[0, 0].item())
print(type(x[0, 0].item()))

tensor(0.8835)
<class 'torch.Tensor'>
0.8835136294364929
<class 'float'>


There are more tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra..., are described [here](https://pytorch.org/docs/stable/torch.html)