### 02. Operations

There are multiple syntaxes for operations. In the following example, we will take a look at the addition operation.

In [1]:
from __future__ import print_function
import torch

In [2]:
# addition: syntax 1
x = torch.rand(5, 3)
y = torch.rand(5, 3)
print(x)
print(y)
print(x + y)

tensor([[0.2424, 0.0949, 0.2620],
        [0.2166, 0.8865, 0.5905],
        [0.2512, 0.1541, 0.9730],
        [0.3663, 0.6274, 0.9021],
        [0.3711, 0.0971, 0.3524]])
tensor([[0.1994, 0.1332, 0.2163],
        [0.1982, 0.6975, 0.5992],
        [0.5440, 0.3290, 0.0749],
        [0.2774, 0.5263, 0.4672],
        [0.2043, 0.0045, 0.3537]])
tensor([[0.4418, 0.2281, 0.4784],
        [0.4149, 1.5840, 1.1897],
        [0.7952, 0.4831, 1.0479],
        [0.6438, 1.1537, 1.3693],
        [0.5754, 0.1015, 0.7061]])


In [3]:
# addition: syntax 2
print(torch.add(x, y))

tensor([[0.4418, 0.2281, 0.4784],
        [0.4149, 1.5840, 1.1897],
        [0.7952, 0.4831, 1.0479],
        [0.6438, 1.1537, 1.3693],
        [0.5754, 0.1015, 0.7061]])


In [4]:
# addition: providing an output tensor as argument
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[0.4418, 0.2281, 0.4784],
        [0.4149, 1.5840, 1.1897],
        [0.7952, 0.4831, 1.0479],
        [0.6438, 1.1537, 1.3693],
        [0.5754, 0.1015, 0.7061]])


In [5]:
# addition: in-place
# adds x to y
y.add_(x)
print(y)

tensor([[0.4418, 0.2281, 0.4784],
        [0.4149, 1.5840, 1.1897],
        [0.7952, 0.4831, 1.0479],
        [0.6438, 1.1537, 1.3693],
        [0.5754, 0.1015, 0.7061]])


Note: any operation that mutates a tensor in-place is post-fixed with an `_`. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

In [6]:
# you can use standard NumPy-like indexing with all bells and whistles:
print(x)
print(x[:, 1])

tensor([[0.2424, 0.0949, 0.2620],
        [0.2166, 0.8865, 0.5905],
        [0.2512, 0.1541, 0.9730],
        [0.3663, 0.6274, 0.9021],
        [0.3711, 0.0971, 0.3524]])
tensor([0.0949, 0.8865, 0.1541, 0.6274, 0.0971])


Resizing: if you want to resize/reshape tensor, you can use `torch.view`

In [7]:
x = torch.rand(4, 4)
print(x)
print('x size:', x.size())
y = x.view(16)
print(y)
print('y size:', y.size())
z = x.view(-1, 8) # the size -1 is inferred from other dimensions, i.e., 4*4/8=2
print(z)
print('z size:', z.size())

tensor([[0.4120, 0.0863, 0.8300, 0.1853],
        [0.5961, 0.2848, 0.4627, 0.5440],
        [0.1737, 0.1720, 0.3070, 0.3970],
        [0.8703, 0.8095, 0.0561, 0.2174]])
x size: torch.Size([4, 4])
tensor([0.4120, 0.0863, 0.8300, 0.1853, 0.5961, 0.2848, 0.4627, 0.5440, 0.1737,
        0.1720, 0.3070, 0.3970, 0.8703, 0.8095, 0.0561, 0.2174])
y size: torch.Size([16])
tensor([[0.4120, 0.0863, 0.8300, 0.1853, 0.5961, 0.2848, 0.4627, 0.5440],
        [0.1737, 0.1720, 0.3070, 0.3970, 0.8703, 0.8095, 0.0561, 0.2174]])
z size: torch.Size([2, 8])


If you have a one element tensor, use `.item()` to get the value as a Python number

In [8]:
x = torch.rand(4, 4)
print(x[0, 0])
print(type(x[0, 0]))
print(x[0, 0].item())
print(type(x[0, 0].item()))

tensor(0.0665)
<class 'torch.Tensor'>
0.0664757490158081
<class 'float'>


There are more tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra..., are described [here](https://pytorch.org/docs/stable/torch.html)