### 02. Operations

There are multiple syntaxes for operations. In the following example, we will take a look at the addition operation.

In [1]:
from __future__ import print_function
import torch

In [2]:
# addition: syntax 1
x = torch.rand(5, 3)
y = torch.rand(5, 3)
print(x)
print(y)
print(x + y)

tensor([[0.0239, 0.4363, 0.1757],
        [0.0702, 0.1715, 0.2826],
        [0.5761, 0.6743, 0.0620],
        [0.0616, 0.6628, 0.1987],
        [0.0765, 0.1421, 0.1481]])
tensor([[0.5487, 0.4603, 0.6245],
        [0.8196, 0.0323, 0.9762],
        [0.6939, 0.9699, 0.7913],
        [0.3334, 0.7927, 0.5660],
        [0.1788, 0.6171, 0.8448]])
tensor([[0.5726, 0.8966, 0.8002],
        [0.8898, 0.2038, 1.2589],
        [1.2700, 1.6442, 0.8534],
        [0.3949, 1.4555, 0.7647],
        [0.2553, 0.7592, 0.9929]])


In [3]:
# addition: syntax 2
print(torch.add(x, y))

tensor([[0.5726, 0.8966, 0.8002],
        [0.8898, 0.2038, 1.2589],
        [1.2700, 1.6442, 0.8534],
        [0.3949, 1.4555, 0.7647],
        [0.2553, 0.7592, 0.9929]])


In [4]:
# addition: providing an output tensor as argument
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

NameError: name 'result' is not defined