### 04. CUDA Tensors

Tensors can be moved onto any device using `.to` method.

In [1]:
from __future__ import print_function
import torch

In [2]:
# let us run this cell only if CUDA is available
# we will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda") # a CUDA device object
    print(device)
    print(type(device))
    x = torch.ones(3, 3)
    print('x in cpu:')
    print(x)

    y = torch.ones_like(x, device=device) # directly create a tensor on GPU
    print('y in gpu:')
    print(y)

    z = x.to(device) + y
    print('z in gpu:')
    print(z)
    print('z in cpu:')
    print(z.to("cpu", torch.double)) # ``.to`` can also change dtype together!

cuda
<class 'torch.device'>
x in cpu:
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
y in gpu:
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')
z in gpu:
tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]], device='cuda:0')
z in cpu:
tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]], dtype=torch.float64)
