### 05. AutoGrad

AutoGrad: automatic differentiation. The `autograd` package provides automatic differentiation for all operations on Tensors.

In [1]:
import torch

create a tensor and set `requires_grad=True` to track computation with it.

In [2]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [3]:
# do a tensor operation
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


`y` was created as a result of an operation, so it has a `grad_fn`.

In [4]:
print(y.grad_fn)

do more operations on `y`

In [5]:
z = y * y * 3
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


`.requires_grad_(...)` changes an existing Tensor's `requires_grad` flag in-place. The input flag defaults to `False` if not given.

In [6]:
a = torch.randn(2, 2)
a = ((a * 3)/(a - 1))
print(a)
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

tensor([[-9.0915,  1.7658],
        [ 1.6180, -1.5116]])
False
True
