### 07. Vector-Jacobian Product

Generally speaking, `torch.autograd` is an engine for computing vector-Jacobian product.

In [1]:
import torch
x = torch.randn(3, requires_grad=True)
print(x)

tensor([-1.0672,  0.4757, -0.2733], requires_grad=True)


In [2]:
y = x * 2
print(y)

tensor([-2.1345,  0.9514, -0.5466], grad_fn=<MulBackward0>)


In [3]:
while y.data.norm() < 1000:
    y = y * 2
print(y)

tensor([-1092.8602,   487.1178,  -279.8656], grad_fn=<MulBackward0>)


Now in this case `y` is no longer a scalar. `torch.autograd` cloud not compute the full Jacobian directly, but if we just want the vector-Jacobian product, simply pass the vector to `backward` as argument:

In [4]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


You can also stop autograd from tracking history on Tensors with `.requires_grad=True` either by wrapping the code block in `with torch.no_grad():`

In [5]:
print(x.requires_grad)
print((x**2).requires_grad)

with torch.no_grad():
    print((x**2).requires_grad)

True
True
False


Or by using `.detach()` to get a new Tensor with the same content but that does not require gradients:

In [6]:
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)
print(x.eq(y).all())

True
False
tensor(True)
