### 08. Pytorch Basics

This pytorch basics tutorial contains more examples for autograd, loading data, input pipline, pretrained model, save and load model.

#### Table of Contents

- [1. Basic autograd example 1](#heading)
- [2. Basic autograd example 2](#heading)
- [3. Loading data from numpy](#heading)
- [4. Input pipline](#heading)
- [5. Input pipline for custom dataset](#heading)
- [6. Pretrained model](#heading)
- [7. Save and load model](#heading)


#### 1. Basic autograd example 1

In [1]:
import torch
import torchvision
import torch.nn as nn
import numpy as np
import torchvision.transforms as transforms

In [2]:
# create tensors
x = torch.tensor(1., requires_grad=True)
w = torch.tensor(2., requires_grad=True)
b = torch.tensor(3., requires_grad=True)

# build a computational graph
# y = 2 * x + 3
y = w * x + b

# compute gradients
y.backward()

# print out the gradients
print(x.grad)
print(w.grad)
print(b.grad)

tensor(2.)
tensor(1.)
tensor(1.)


#### 2. Basic autograd example 2

In [3]:
# create tensors of shape (10, 3) and (10, 2)
x = torch.randn(10, 3)
y = torch.randn(10, 2)
print(f'x: {x}')
print(f'y: {y}')

x: tensor([[-1.5429,  1.8926, -1.0917],
        [-2.1357,  0.7081,  0.3361],
        [ 0.5059, -0.2486, -0.6637],
        [ 0.4491,  0.1497, -0.7409],
        [-0.4214,  1.0621,  0.5324],
        [ 1.3481, -0.2930, -0.0310],
        [ 0.1145, -0.2669,  0.3149],
        [-0.4001, -1.7815,  0.5797],
        [-0.3314,  0.6963,  1.2000],
        [-0.3229, -1.1514,  0.2574]])
y: tensor([[ 0.2439,  0.0140],
        [-0.8807, -1.1382],
        [ 1.4701,  1.4902],
        [ 0.9750,  0.8559],
        [ 1.9366,  0.9416],
        [ 0.0781,  0.4580],
        [-1.4200,  0.0593],
        [ 0.7707, -0.4604],
        [ 0.2901,  0.8110],
        [ 1.0831, -0.1545]])


`torch.nn.Linear(in_features, out_features, bias=True)` applies a linear transformation to the incoming data $y=xA^{T}+b$

In [4]:
# build a fully connected layer
linear = nn.Linear(3, 2)
print('w: ', linear.weight)
print('b: ', linear.bias)
print('shape of w: ', linear.weight.size())
print('shape of b: ', linear.bias.size())

w:  Parameter containing:
tensor([[ 0.3220,  0.3125, -0.3585],
        [-0.5166,  0.3031, -0.1991]], requires_grad=True)
b:  Parameter containing:
tensor([-0.4710,  0.4945], requires_grad=True)
shape of w:  torch.Size([2, 3])
shape of b:  torch.Size([2])


In [5]:
# build loss function and optimizer
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(linear.parameters(), lr=0.01)

# forward pass
pred = linear(x)
print(pred)

tensor([[ 0.0150,  2.0826],
        [-1.0579,  1.7456],
        [-0.1479,  0.2900],
        [-0.0140,  0.4554],
        [-0.4657,  0.9281],
        [-0.1174, -0.2846],
        [-0.6304,  0.2917],
        [-1.3644,  0.0459],
        [-0.7903,  0.6378],
        [-1.0271,  0.2611]], grad_fn=<AddmmBackward>)


In [6]:
# compute loss
loss = criterion(pred, y)
print('loss: ', loss.item())

loss:  1.7776283025741577


In [7]:
# backward pass
loss.backward()

# print out the gradients
print('dL/dw: ', linear.weight.grad)
print('dL/db: ', linear.bias.grad)

dL/dw:  tensor([[ 0.2202,  0.2471, -0.2105],
        [-1.1386,  0.4836,  0.0086]])
dL/db:  tensor([-1.0147,  0.3577])


In [8]:
# 1-step gradient descent
# optimizer.step()

# you can also perform gradient descent at the low level
linear.weight.data.sub_(0.01 * linear.weight.grad.data)
linear.bias.data.sub_(0.01 * linear.bias.grad.data)

# print out the loss after 1-step gradient descent
pred = linear(x)
loss = criterion(pred, y)
print('loss after 1-step optimization: ', loss.item())

loss after 1-step optimization:  1.7493928670883179


### 3. Loading data from numpy

In [9]:
# create a numpy array
x = np.array([[1, 2], [3, 4]])
print('x: ', x)
print(type(x))

x:  [[1 2]
 [3 4]]
<class 'numpy.ndarray'>


In [10]:
# convert the numpy array to a torch tensor
y = torch.from_numpy(x)
print('y: ', y)
print(type(y))

y:  tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
<class 'torch.Tensor'>


In [11]:
# convert the torch tensor to a numpy array
z = y.numpy()
print('z: ', z)
print(type(z))

z:  [[1 2]
 [3 4]]
<class 'numpy.ndarray'>
