### 08. Pytorch Basics

This pytorch basics tutorial contains more examples for autograd, loading data, input pipline, pretrained model, save and load model.

#### Table of Contents

- [1. Basic autograd example 1](#heading)
- [2. Basic autograd example 2](#heading)
- [3. Loading data from numpy](#heading)

#### 1. Basic autograd example 1

In [1]:
import torch
import torchvision
import torch.nn as nn
import numpy as np
import torchvision.transforms as transforms

In [2]:
# create tensors
x = torch.tensor(1., requires_grad=True)
w = torch.tensor(2., requires_grad=True)
b = torch.tensor(3., requires_grad=True)

# build a computational graph
# y = 2 * x + 3
y = w * x + b

# compute gradients
y.backward()

# print out the gradients
print(x.grad)
print(w.grad)
print(b.grad)

tensor(2.)
tensor(1.)
tensor(1.)


#### 2. Basic autograd example 2

In [3]:
# create tensors of shape (10, 3) and (10, 2)
x = torch.randn(10, 3)
y = torch.randn(10, 2)
print(f'x: {x}')
print(f'y: {y}')

x: tensor([[-0.0748, -0.2835, -2.3969],
        [ 1.0028, -0.3483, -1.0015],
        [ 0.1345, -0.7380,  0.3367],
        [ 0.3890,  0.3832,  0.7038],
        [-0.6811, -0.6285,  0.1993],
        [-0.6119,  0.9692, -0.6272],
        [ 0.8341,  1.8730,  0.1967],
        [ 0.5010, -0.9443,  0.3819],
        [ 0.0568,  0.2196, -1.9067],
        [-0.3059, -0.7725, -1.1613]])
y: tensor([[ 0.6416,  1.1953],
        [-0.6853,  1.6039],
        [-0.7574, -0.6724],
        [ 0.4923,  0.7073],
        [-0.8901, -1.2171],
        [-1.2878, -0.6040],
        [ 0.0496, -0.1543],
        [-0.2024, -0.8165],
        [ 1.6689, -0.5598],
        [ 0.2624, -1.8407]])


`torch.nn.Linear(in_features, out_features, bias=True)` applies a linear transformation to the incoming data $y=xA^{T}+b$

In [4]:
# build a fully connected layer
linear = nn.Linear(3, 2)
print('w: ', linear.weight)
print('b: ', linear.bias)
print('shape of w: ', linear.weight.size())
print('shape of b: ', linear.bias.size())

w:  Parameter containing:
tensor([[-0.4679, -0.1080,  0.5265],
        [ 0.5600,  0.1219, -0.1688]], requires_grad=True)
b:  Parameter containing:
tensor([-0.4259, -0.5092], requires_grad=True)
shape of w:  torch.Size([2, 3])
shape of b:  torch.Size([2])


In [5]:
# build loss function and optimizer
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(linear.parameters(), lr=0.01)

# forward pass
pred = linear(x)
print(pred)

tensor([[-1.6223, -0.1811],
        [-1.3849,  0.1789],
        [-0.2319, -0.5807],
        [-0.2788, -0.3635],
        [ 0.0657, -1.0010],
        [-0.5745, -0.6279],
        [-0.9149,  0.1530],
        [-0.3573, -0.4082],
        [-1.4801, -0.1288],
        [-0.8108, -0.5787]], grad_fn=<AddmmBackward>)


In [6]:
# compute loss
loss = criterion(pred, y)
print('loss: ', loss.item())

loss:  1.354860544204712


In [7]:
# backward pass
loss.backward()

# print out the gradients
print('dL/dw: ', linear.weight.grad)
print('dL/db: ', linear.bias.grad)

dL/dw:  tensor([[-0.2581, -0.1230,  1.2506],
        [-0.1763, -0.0440,  0.1991]])
dL/db:  tensor([-0.6882, -0.1180])


In [8]:
# 1-step gradient descent
# optimizer.step()

# you can also perform gradient descent at the low level
linear.weight.data.sub_(0.01 * linear.weight.grad.data)
linear.bias.data.sub_(0.01 * linear.bias.grad.data)

# print out the loss after 1-step gradient descent
pred = linear(x)
loss = criterion(pred, y)
print('loss after 1-step optimization: ', loss.item())

loss after 1-step optimization:  1.3329777717590332


### 3. Loading data from numpy

In [9]:
# create a numpy array
x = np.array([[1, 2], [3, 4]])
print('x: ', x)
print(type(x))

x:  [[1 2]
 [3 4]]
<class 'numpy.ndarray'>


In [10]:
# convert the numpy array to a torch tensor
y = torch.from_numpy(x)
print('y: ', y)
print(type(y))

y:  tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
<class 'torch.Tensor'>


In [11]:
# convert the torch tensor to a numpy array
z = y.numpy()
print('z: ', z)
print(type(z))

z:  [[1 2]
 [3 4]]
<class 'numpy.ndarray'>
